stages:
  - build
  - deploy_test

variables:
  PROJECT_NAME: nginx-phpfpm
  COMMIT_BRANCH_NAME: ${CI_COMMIT_REF_NAME}
  PIPELINE_ID: ${CI_PIPELINE_ID}
build:
  stage: build
  tags:
    - nginx-phpfpm
  script:
    - echo 构建
    - pwd
    - ls -la
  only:
    - master
deploy_test:
  stage: deploy_test
  tags:
      - nginx-phpfpm
  script:
    - echo ${PROJECT_NAME} ${COMMIT_BRANCH_NAME} ${PIPELINE_ID}
    - docker info
    - pwd
    - ls -la
    - docker ps
    - docker images
  only:
    - master
