stages:
  - build
  - push

variables:
  HARBOR_HOST: harbor.vchangyi.com
  USER_NAME: qiuapeng
  USER_PASS: DUyP3e6YGoo2TMdMio
  INAGE_NAMESPACE: library
  INAGE_NAME: nginx-phpfpm-supervisord
  IMAGE_ADDRESS: $HARBOR_HOST/$INAGE_NAMESPACE/$INAGE_NAME:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID}

build:
  stage: build
  tags:
    - nginx-phpfpm
  script:
    - docker build -t $IMAGE_ADDRESS .
  only:
    - master

deploy:
  stage: push
  tags:
    - nginx-phpfpm
  before_script:
    - docker login $HARBOR_HOST -u $USER_NAME -p $USER_PASS
  script:
    - docker push $IMAGE_ADDRESS
  after_script:
    - docker rmi -f $IMAGE_ADDRESS
  only:
    - master
