stages:
  - build
  - deploy_test

variables:
  PROJECT_NAME: nginx-phpfpm
build:
  stage: build
  tags:
    - nginx-phpfpm
  script:
    - echo 构建
    - pwd
    - ls -la
    - docker build test:1.0
  only:
    - master
deploy_test:
  stage: deploy_test
  tags:
      - nginx-phpfpm
  script:
    - echo 2222222222
    - pwd
    - ls -la
    - docker ps
    - docker images
  only:
    - master
