stages:
  - build
  - deploy_test
  -
variables:
  PROJECT_NAME: nginx-phpfpm
build:
  stage: build
  tags:
    - nginx-phpfpm
  script:
    - echo 11111111111
  only:
    - master
deploy_test:
  stage: deploy_test
  tags:
      - nginx-phpfpm
  script:
    - echo 2222222222
  only:
    - master
